// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UnderSea.DAL.Context;

namespace UnderSea.DAL.Migrations
{
    [DbContext(typeof(UnderSeaDbContext))]
    partial class UnderSeaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("UnderSea.DAL.Models.Attack", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AttackerUserId")
                        .HasColumnType("int");

                    b.Property<int>("DefenderUserId")
                        .HasColumnType("int");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AttackerUserId");

                    b.HasIndex("DefenderUserId");

                    b.HasIndex("GameId");

                    b.ToTable("Attacks");
                });

            modelBuilder.Entity("UnderSea.DAL.Models.Buildings.Building", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BuildingGroupId")
                        .HasColumnType("int");

                    b.Property<int>("ConstructionTimeLeft")
                        .HasColumnType("int");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.Property<int>("UnderConstructionCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BuildingGroupId");

                    b.HasIndex("TypeId");

                    b.ToTable("Buildings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BuildingGroupId = 1,
                            ConstructionTimeLeft = 0,
                            Count = 4,
                            TypeId = 1,
                            UnderConstructionCount = 0
                        },
                        new
                        {
                            Id = 2,
                            BuildingGroupId = 1,
                            ConstructionTimeLeft = 0,
                            Count = 1,
                            TypeId = 2,
                            UnderConstructionCount = 0
                        },
                        new
                        {
                            Id = 3,
                            BuildingGroupId = 2,
                            ConstructionTimeLeft = 0,
                            Count = 4,
                            TypeId = 1,
                            UnderConstructionCount = 0
                        },
                        new
                        {
                            Id = 4,
                            BuildingGroupId = 2,
                            ConstructionTimeLeft = 0,
                            Count = 1,
                            TypeId = 2,
                            UnderConstructionCount = 0
                        });
                });

            modelBuilder.Entity("UnderSea.DAL.Models.Buildings.BuildingGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("Id");

                    b.ToTable("BuildingGroup");

                    b.HasData(
                        new
                        {
                            Id = 1
                        },
                        new
                        {
                            Id = 2
                        });
                });

            modelBuilder.Entity("UnderSea.DAL.Models.Buildings.BuildingType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CoralBonus")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PopulationBonus")
                        .HasColumnType("int");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<int>("UnitStorage")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("BuildingType");

                    b.HasDiscriminator<string>("Discriminator").HasValue("BuildingType");
                });

            modelBuilder.Entity("UnderSea.DAL.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AttackingArmyId")
                        .HasColumnType("int");

                    b.Property<int>("BuildingGroupId")
                        .HasColumnType("int");

                    b.Property<int>("BuildingTimeLeft")
                        .HasColumnType("int");

                    b.Property<int>("Coral")
                        .HasColumnType("int");

                    b.Property<int>("DefendingArmyId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Pearl")
                        .HasColumnType("int");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<int>("UpgradeTimeLeft")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AttackingArmyId");

                    b.HasIndex("BuildingGroupId");

                    b.HasIndex("DefendingArmyId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AttackingArmyId = 1,
                            BuildingGroupId = 1,
                            BuildingTimeLeft = 0,
                            Coral = 100000,
                            DefendingArmyId = 2,
                            Name = "First Country",
                            Pearl = 100000,
                            Score = 0,
                            UpgradeTimeLeft = 0,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            AttackingArmyId = 3,
                            BuildingGroupId = 2,
                            BuildingTimeLeft = 0,
                            Coral = 100000,
                            DefendingArmyId = 4,
                            Name = "Another Country",
                            Pearl = 100000,
                            Score = 0,
                            UpgradeTimeLeft = 0,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("UnderSea.DAL.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CoralPictureUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PearlPictureUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Round")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Game");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CoralPictureUrl = "",
                            PearlPictureUrl = "",
                            Round = 1
                        });
                });

            modelBuilder.Entity("UnderSea.DAL.Models.Units.Unit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AttackId")
                        .HasColumnType("int");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.Property<int>("UnitGroupId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AttackId");

                    b.HasIndex("TypeId");

                    b.HasIndex("UnitGroupId");

                    b.ToTable("Units");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Count = 0,
                            TypeId = 1,
                            UnitGroupId = 1
                        },
                        new
                        {
                            Id = 2,
                            Count = 0,
                            TypeId = 2,
                            UnitGroupId = 1
                        },
                        new
                        {
                            Id = 3,
                            Count = 0,
                            TypeId = 3,
                            UnitGroupId = 1
                        },
                        new
                        {
                            Id = 4,
                            Count = 20,
                            TypeId = 1,
                            UnitGroupId = 2
                        },
                        new
                        {
                            Id = 5,
                            Count = 20,
                            TypeId = 2,
                            UnitGroupId = 2
                        },
                        new
                        {
                            Id = 6,
                            Count = 20,
                            TypeId = 3,
                            UnitGroupId = 2
                        },
                        new
                        {
                            Id = 7,
                            Count = 0,
                            TypeId = 1,
                            UnitGroupId = 3
                        },
                        new
                        {
                            Id = 8,
                            Count = 0,
                            TypeId = 2,
                            UnitGroupId = 3
                        },
                        new
                        {
                            Id = 9,
                            Count = 0,
                            TypeId = 3,
                            UnitGroupId = 3
                        },
                        new
                        {
                            Id = 10,
                            Count = 10,
                            TypeId = 1,
                            UnitGroupId = 4
                        },
                        new
                        {
                            Id = 11,
                            Count = 20,
                            TypeId = 2,
                            UnitGroupId = 4
                        },
                        new
                        {
                            Id = 12,
                            Count = 40,
                            TypeId = 3,
                            UnitGroupId = 4
                        });
                });

            modelBuilder.Entity("UnderSea.DAL.Models.Units.UnitGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("Id");

                    b.ToTable("UnitGroup");

                    b.HasData(
                        new
                        {
                            Id = 1
                        },
                        new
                        {
                            Id = 2
                        },
                        new
                        {
                            Id = 3
                        },
                        new
                        {
                            Id = 4
                        });
                });

            modelBuilder.Entity("UnderSea.DAL.Models.Units.UnitType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("AttackScore")
                        .HasColumnType("float");

                    b.Property<int>("CoralCostPerTurn")
                        .HasColumnType("int");

                    b.Property<double>("DefenseScore")
                        .HasColumnType("float");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PearlCostPerTurn")
                        .HasColumnType("int");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("UnitType");

                    b.HasDiscriminator<string>("Discriminator").HasValue("UnitType");
                });

            modelBuilder.Entity("UnderSea.DAL.Models.Upgrades.Upgrade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("TypeId");

                    b.ToTable("Upgrade");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryId = 1,
                            State = 3,
                            TypeId = 1
                        },
                        new
                        {
                            Id = 2,
                            CountryId = 1,
                            State = 1,
                            TypeId = 2
                        },
                        new
                        {
                            Id = 3,
                            CountryId = 1,
                            State = 3,
                            TypeId = 3
                        },
                        new
                        {
                            Id = 4,
                            CountryId = 1,
                            State = 3,
                            TypeId = 4
                        },
                        new
                        {
                            Id = 5,
                            CountryId = 1,
                            State = 3,
                            TypeId = 5
                        },
                        new
                        {
                            Id = 6,
                            CountryId = 1,
                            State = 3,
                            TypeId = 6
                        },
                        new
                        {
                            Id = 7,
                            CountryId = 2,
                            State = 1,
                            TypeId = 1
                        },
                        new
                        {
                            Id = 8,
                            CountryId = 2,
                            State = 3,
                            TypeId = 2
                        },
                        new
                        {
                            Id = 9,
                            CountryId = 2,
                            State = 3,
                            TypeId = 3
                        },
                        new
                        {
                            Id = 10,
                            CountryId = 2,
                            State = 1,
                            TypeId = 4
                        },
                        new
                        {
                            Id = 11,
                            CountryId = 2,
                            State = 3,
                            TypeId = 5
                        },
                        new
                        {
                            Id = 12,
                            CountryId = 2,
                            State = 3,
                            TypeId = 6
                        });
                });

            modelBuilder.Entity("UnderSea.DAL.Models.Upgrades.UpgradeType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AttackBonusPercentage")
                        .HasColumnType("int");

                    b.Property<int>("CoralProductionBonusPercentage")
                        .HasColumnType("int");

                    b.Property<int>("DefenseBonusPercentage")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PearlProductionBonusPercentage")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("UpgradeType");

                    b.HasDiscriminator<string>("Discriminator").HasValue("UpgradeType");
                });

            modelBuilder.Entity("UnderSea.DAL.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<int>("Place")
                        .HasColumnType("int");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "edd19a93-c394-4c49-9e7f-52ac0e7ee2e8",
                            EmailConfirmed = false,
                            GameId = 1,
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            Place = 1,
                            Score = 100,
                            TwoFactorEnabled = false,
                            UserName = "First User"
                        },
                        new
                        {
                            Id = 2,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "8b4706c5-8201-4c12-99ac-3c382c511a59",
                            EmailConfirmed = false,
                            GameId = 1,
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            Place = 2,
                            Score = 50,
                            TwoFactorEnabled = false,
                            UserName = "Second User"
                        });
                });

            modelBuilder.Entity("UnderSea.DAL.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("UnderSea.DAL.Models.Buildings.FlowManager", b =>
                {
                    b.HasBaseType("UnderSea.DAL.Models.Buildings.BuildingType");

                    b.HasDiscriminator().HasValue("FlowManager");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            CoralBonus = 200,
                            Description = "200 egységnek nyújt szállást",
                            ImageUrl = "majd/lesz/kep.jpeg",
                            Name = "Áramlásirányító",
                            PopulationBonus = 50,
                            Price = 1000,
                            Score = 0,
                            UnitStorage = 0
                        });
                });

            modelBuilder.Entity("UnderSea.DAL.Models.Buildings.ReefCastle", b =>
                {
                    b.HasBaseType("UnderSea.DAL.Models.Buildings.BuildingType");

                    b.HasDiscriminator().HasValue("ReefCastle");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CoralBonus = 0,
                            Description = "50 ember-t ad a népességhez, 200 krumplit termel körönként",
                            ImageUrl = "majd/lesz/kep.jpeg",
                            Name = "Zátonyvár",
                            PopulationBonus = 0,
                            Price = 1000,
                            Score = 0,
                            UnitStorage = 200
                        });
                });

            modelBuilder.Entity("UnderSea.DAL.Models.Units.CombatSeaHorse", b =>
                {
                    b.HasBaseType("UnderSea.DAL.Models.Units.UnitType");

                    b.ToTable("UnitType");

                    b.HasDiscriminator().HasValue("CombatSeaHorse");

                    b.HasData(
                        new
                        {
                            Id = 3,
                            AttackScore = 2.0,
                            CoralCostPerTurn = 1,
                            DefenseScore = 6.0,
                            ImageUrl = "majd/lesz/kep.jpeg",
                            Name = "Csatacsikó",
                            PearlCostPerTurn = 1,
                            Price = 50,
                            Score = 0
                        });
                });

            modelBuilder.Entity("UnderSea.DAL.Models.Units.LaserShark", b =>
                {
                    b.HasBaseType("UnderSea.DAL.Models.Units.UnitType");

                    b.ToTable("UnitType");

                    b.HasDiscriminator().HasValue("LaserShark");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AttackScore = 5.0,
                            CoralCostPerTurn = 2,
                            DefenseScore = 5.0,
                            ImageUrl = "majd/lesz/kep.jpeg",
                            Name = "Lézercápa",
                            PearlCostPerTurn = 3,
                            Price = 100,
                            Score = 0
                        });
                });

            modelBuilder.Entity("UnderSea.DAL.Models.Units.StormSeal", b =>
                {
                    b.HasBaseType("UnderSea.DAL.Models.Units.UnitType");

                    b.ToTable("UnitType");

                    b.HasDiscriminator().HasValue("StormSeal");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            AttackScore = 6.0,
                            CoralCostPerTurn = 1,
                            DefenseScore = 2.0,
                            ImageUrl = "majd/lesz/kep.jpeg",
                            Name = "Rohamfóka",
                            PearlCostPerTurn = 1,
                            Price = 50,
                            Score = 0
                        });
                });

            modelBuilder.Entity("UnderSea.DAL.Models.Upgrades.Alchemy", b =>
                {
                    b.HasBaseType("UnderSea.DAL.Models.Upgrades.UpgradeType");

                    b.HasDiscriminator().HasValue("Alchemy");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AttackBonusPercentage = 0,
                            CoralProductionBonusPercentage = 30,
                            DefenseBonusPercentage = 0,
                            Description = "növeli a beszedett adót 30%-kal",
                            ImageUrl = "majd/kesobb/lesz/kep.jpg",
                            Name = "Alkímia",
                            PearlProductionBonusPercentage = 0
                        });
                });

            modelBuilder.Entity("UnderSea.DAL.Models.Upgrades.CoralWall", b =>
                {
                    b.HasBaseType("UnderSea.DAL.Models.Upgrades.UpgradeType");

                    b.HasDiscriminator().HasValue("CoralWall");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            AttackBonusPercentage = 0,
                            CoralProductionBonusPercentage = 0,
                            DefenseBonusPercentage = 20,
                            Description = "növeli a védelmi pontokat 20%-kal",
                            ImageUrl = "majd/kesobb/lesz/kep.jpg",
                            Name = "Korallfal",
                            PearlProductionBonusPercentage = 0
                        });
                });

            modelBuilder.Entity("UnderSea.DAL.Models.Upgrades.MudHarvester", b =>
                {
                    b.HasBaseType("UnderSea.DAL.Models.Upgrades.UpgradeType");

                    b.HasDiscriminator().HasValue("MudHarvester");

                    b.HasData(
                        new
                        {
                            Id = 3,
                            AttackBonusPercentage = 0,
                            CoralProductionBonusPercentage = 15,
                            DefenseBonusPercentage = 0,
                            Description = "növeli a korall termesztést 15%-kal",
                            ImageUrl = "majd/kesobb/lesz/kep.jpg",
                            Name = "Iszapkombájn",
                            PearlProductionBonusPercentage = 0
                        });
                });

            modelBuilder.Entity("UnderSea.DAL.Models.Upgrades.MudTractor", b =>
                {
                    b.HasBaseType("UnderSea.DAL.Models.Upgrades.UpgradeType");

                    b.HasDiscriminator().HasValue("MudTractor");

                    b.HasData(
                        new
                        {
                            Id = 4,
                            AttackBonusPercentage = 0,
                            CoralProductionBonusPercentage = 10,
                            DefenseBonusPercentage = 0,
                            Description = "növeli a krumpli termesztést 10%-kal",
                            ImageUrl = "majd/kesobb/lesz/kep.jpg",
                            Name = "Iszaptraktor",
                            PearlProductionBonusPercentage = 0
                        });
                });

            modelBuilder.Entity("UnderSea.DAL.Models.Upgrades.SonarCannon", b =>
                {
                    b.HasBaseType("UnderSea.DAL.Models.Upgrades.UpgradeType");

                    b.HasDiscriminator().HasValue("SonarCannon");

                    b.HasData(
                        new
                        {
                            Id = 5,
                            AttackBonusPercentage = 20,
                            CoralProductionBonusPercentage = 0,
                            DefenseBonusPercentage = 0,
                            Description = "növeli a támadópontokat 20%-kal",
                            ImageUrl = "majd/kesobb/lesz/kep.jpg",
                            Name = "Szonárágyú",
                            PearlProductionBonusPercentage = 0
                        });
                });

            modelBuilder.Entity("UnderSea.DAL.Models.Upgrades.UnderwaterMartialArts", b =>
                {
                    b.HasBaseType("UnderSea.DAL.Models.Upgrades.UpgradeType");

                    b.HasDiscriminator().HasValue("UnderwaterMartialArts");

                    b.HasData(
                        new
                        {
                            Id = 6,
                            AttackBonusPercentage = 10,
                            CoralProductionBonusPercentage = 0,
                            DefenseBonusPercentage = 10,
                            Description = "növeli a védelmi és támadóerőt 10%-kal",
                            ImageUrl = "majd/kesobb/lesz/kep.jpg",
                            Name = "Vízalatti harcművészetek",
                            PearlProductionBonusPercentage = 0
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("UnderSea.DAL.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("UnderSea.DAL.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("UnderSea.DAL.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("UnderSea.DAL.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("UnderSea.DAL.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("UnderSea.DAL.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("UnderSea.DAL.Models.Attack", b =>
                {
                    b.HasOne("UnderSea.DAL.Models.User", "AttackerUser")
                        .WithMany()
                        .HasForeignKey("AttackerUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("UnderSea.DAL.Models.User", "DefenderUser")
                        .WithMany()
                        .HasForeignKey("DefenderUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("UnderSea.DAL.Models.Game", null)
                        .WithMany("Attacks")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("UnderSea.DAL.Models.Buildings.Building", b =>
                {
                    b.HasOne("UnderSea.DAL.Models.Buildings.BuildingGroup", null)
                        .WithMany("Buildings")
                        .HasForeignKey("BuildingGroupId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("UnderSea.DAL.Models.Buildings.BuildingType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("UnderSea.DAL.Models.Country", b =>
                {
                    b.HasOne("UnderSea.DAL.Models.Units.UnitGroup", "AttackingArmy")
                        .WithMany()
                        .HasForeignKey("AttackingArmyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("UnderSea.DAL.Models.Buildings.BuildingGroup", "BuildingGroup")
                        .WithMany()
                        .HasForeignKey("BuildingGroupId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("UnderSea.DAL.Models.Units.UnitGroup", "DefendingArmy")
                        .WithMany()
                        .HasForeignKey("DefendingArmyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("UnderSea.DAL.Models.User", "User")
                        .WithOne("Country")
                        .HasForeignKey("UnderSea.DAL.Models.Country", "UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("UnderSea.DAL.Models.Units.Unit", b =>
                {
                    b.HasOne("UnderSea.DAL.Models.Attack", null)
                        .WithMany("UnitList")
                        .HasForeignKey("AttackId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("UnderSea.DAL.Models.Units.UnitType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("UnderSea.DAL.Models.Units.UnitGroup", null)
                        .WithMany("Units")
                        .HasForeignKey("UnitGroupId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("UnderSea.DAL.Models.Upgrades.Upgrade", b =>
                {
                    b.HasOne("UnderSea.DAL.Models.Country", null)
                        .WithMany("Upgrades")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("UnderSea.DAL.Models.Upgrades.UpgradeType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("UnderSea.DAL.Models.User", b =>
                {
                    b.HasOne("UnderSea.DAL.Models.Game", null)
                        .WithMany("Users")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
